# Generated by Django 4.0.4 on 2022-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_remove_food_id_alter_food_email_alter_food_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
